apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harness-demo
  template:
    metadata:
      labels:
        app: harness-demo
    spec:
      containers:
      - image: 24987503353.dkr.ecr.us-east-2.amazonaws.com/jfrog:local
        name: harness-demo
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harness
